# -*- coding: utf-8 -*-
"""Problema 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zNbxnqrNg-qzw5g0ZlShjqArGxtvUvBv

Problema 2. Hacer un programa que imprima los números del -100 al 200 que sean divisibles entre 6 (con resto 0)
"""

# Problema 2
# Imprimir los números del -100 al 200 divisibles entre 6

for i in range(-100, 201):
    if i % 6 == 0:
      # si el resto es 0
        print(i)