# -*- coding: utf-8 -*-
"""Problema 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1uuroz2QwYU4514PT9S5ypV__mUxTPK

Problema 3.
Pseudocódigo, sumador y comparador de dos números Realiza el algoritmo para un sumador de dos números. Si el resultado es menor a 200 se mostrará el mensaje "menor a 200", si el resultado es mayor a 200, pero menor a 250 se mostrará el mensaje "mayor a 200", pero si es mayor a 250 se mostrará el mensaje "mayor a 250".
"""

# Problema 3
# Programa que suma dos números y muestra mensajes según el resultado

# Entrada de datos
numero1 = float(input("Ingrese el primer número: "))
numero2 = float(input("Ingrese el segundo número: "))

# Proceso: sumamos ambos números
suma = numero1 + numero2

# Condicionales
if suma < 200:
    resultado = "menor a 200"
elif 200 < suma < 250:
    resultado = "mayor a 200 y menor a 250"
else:
    resultado = "mayor a 250"

# Salida
print(f"La suma es {suma}, y el resultado es: {resultado}")