# -*- coding: utf-8 -*-
"""Problema 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H1uuroz2QwYU4514PT9S5ypV__mUxTPK

Problema 4. Pseudocódigo, Calculador de perfil
Generar un programa que combine variables, tipos de datos y una condicional en Python (hacer una función que evalúe si el usuario es mayor de edad y si le gusta la música urbana, que envíe diferentes textos según la respuesta del usuario)
"""

# Problema 4
# Calculador de perfil según edad y preferencia musical

def perfil_usuario(edad, gusta_musica_urbana):
    if edad > 18 and gusta_musica_urbana:
        return "Eres mayor de edad y te gusta la música urbana"
    else:
        return "No eres mayor de edad o no te gusta la música urbana"

# Entrada de datos
edad = int(input("Ingrese su edad: "))
gusta = input("¿Te gusta la música urbana? (si/no): ")

# Transformamos la respuesta en booleano
gusta_musica_urbana = (gusta == "si")

# Resultado
print(perfil_usuario(edad, gusta_musica_urbana))