# -*- coding: utf-8 -*-
"""Problema 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9oKSEmtxEbrhFnnKX2-DYv8sdN36yII

Problema 1.
Hacer un programa que imprima los números del -100 al 200.
"""

# Problema 1
# Imprimir los números del -100 al 200

for i in range(-100, 201):
    print(i)