# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1itWWt-RrvCWmSALZcJFzJ5lgAoF0sVFU

Problema 1.
Hacer un programa que imprima los números del -100 al 200.
"""

# Problema 1
# Imprimir los números del -100 al 200

for i in range(-100, 201):
    print(i)

"""Problema 2.
Hacer un programa que imprima los números del -100 al 200 que sean divisibles entre 6 (con resto 0)
"""

# Problema 2
# Imprimir los números del -100 al 200 divisibles entre 6

for i in range(-100, 201):
    if i % 6 == 0:
      # si el resto es 0
        print(i)

"""Problema 3.
Pseudocódigo, sumador y comparador de dos números Realiza el algoritmo para un sumador de dos números. Si el resultado es menor a 200 se mostrará el mensaje "menor a 200", si el resultado es mayor a 200, pero menor a 250 se mostrará el mensaje "mayor a 200", pero si es mayor a 250 se mostrará el mensaje "mayor a 250".
"""

# Problema 3
# Sumador y comparador de dos números

# Entrada de datos
numero1 = float(input("Ingrese el primer número: "))
numero2 = float(input("Ingrese el segundo número: "))

# Proceso
suma = numero1 + numero2

# Condicionales
if suma < 200:
    resultado = "menor a 200"
elif 200 < suma < 250:
    resultado = "mayor a 200 y menor a 250"
else:
    resultado = "mayor a 250"

# Salida
print(f"La suma es {suma}, y el resultado es: {resultado}")

"""Problema 4. Pseudocódigo, Calculador de perfil
Generar un programa que combine variables, tipos de datos y una condicional en Python (hacer una función que evalúe si el usuario es mayor de edad y si le gusta la música urbana, que envíe diferentes textos según la respuesta del usuario)

"""

# Problema 4
# Calculador de perfil según edad y preferencia musical

def perfil_usuario(edad, gusta_musica_urbana):
    if edad > 18 and gusta_musica_urbana:
        return "Eres mayor de edad y te gusta la música urbana"
    else:
        return "No eres mayor de edad o no te gusta la música urbana"

# Entrada de datos
edad = int(input("Ingrese su edad: "))
gusta = input("¿Te gusta la música urbana? (si/no): ")

# Transformamos la respuesta en booleano
gusta_musica_urbana = (gusta == "si")

# Resultado
print(perfil_usuario(edad, gusta_musica_urbana))
